steps:
  - label: ":gradle: :package:"
#    command: "./gradlew --build-cache clean assemble"
    command: echo "Hello"
#    artifact_paths: "project/build/libs/*.jar"
#    plugins:
#      - docker-compose#v3.5.0:
#          run: gradle
#          config: .buildkite/docker-compose.yml
