env:
  ANDROID_HOME: /Users/zemikone/Library/Android/sdk

steps:
  - label: ":gradle: :package:"
#    command: "./gradlew --build-cache clean assemble"
    commands:
      - >-
        ./gradlew
        assembleDebug

#    artifact_paths: "project/build/libs/*.jar"
#    plugins:
#      - docker-compose#v3.5.0:
#          run: gradle
#          config: .buildkite/docker-compose.yml
