env:
  ANDROID_HOME: /Users/zemikone/Library/Android/sdk

steps:
  - label: ":android: Build Android App"
    command:
      - ./gradlew assembleDebug

  - label: ":android: Run Unit Tests"
    command:
      - ./gradlew testDebugUnitTest
